### ISSUE TITLE
[Suggestion] Target your feelings

### ISSUE THREAD

**Issue by mitya12342** [zachrocks22/ChatFeelings#3]
Hello! I really love and appreciate your plugin. Can you do so, that we can optionally specify the location where to kiss/punch/bite/anything. It would be great for roleplay and also really cute :3
Like `/bite Blackout_SND leg`

> You sink your teeth into Blackout_SND's leg.

> Blackout_SND punches you into the face. Ouch!

Thank you <3

**Comment by zachrocks22** [comment]
Hi there. I very much like that idea, however it would be very difficult to add all those message variations to all feelings. But if I understand correctly, you would just want those added to kiss/punch & bite? If so, that may be doable in the near future. At the moment I am focused on fixing up some bugs still left in regarding /cf ignore and a few others. After I can get those cleared out, I'll see what I can do about adding this feature in an upcoming update!

Thanks again!
:)

**Comment by mitya12342** [comment]
Yea, i think it would be better to add a placeholder. If there are no second argument, just use current messages, if there are, a message with placeholder. It would be easier to do a translation like that. I wish i could help, if i knew java.

Thank u

**Comment by zachrocks22** [comment]
I thought about doing a placeholder solution myself, but I'm afraid I'd run into issues getting things to be grammatically correct for all messages. But it's worth a shot. I'll add it to my "Upcoming Feature" list!

**Comment by zachrocks22** [comment]
Working on prototypes of this feature as we speak, will be rolling out pre-releases on GitHub for testing with this hopefully soon!

**Comment by zachrocks22** [comment]
Delaying this feature as bugs that need fixing have popped up at the moment.

**Comment by zachrocks22** [comment]
I feel that this feature just isn't going to add as much to the plugin and will just over complicate things further. If you have any other suggestions, feel free to[ join our support discord](https://discord.gg/6ugXPfX) and let me know!
