### ISSUE TITLE
annoying metrics disabled message

### ISSUE THREAD

**Issue by madtomic** [zachrocks22/ChatFeelings#4]
Please remove this message when OP logs on the server or a disable option for the message. Thanks

I am using v2.0.1 for Minecraft 1.12.2  Do you still have this source for this legacy branch? I can remove this myself if you can release the legacy source for this version.

**Comment by zachrocks22** [comment]
Hi there! Are you talking about the update message? If so, set update-notify to false in your ChatFeeling's configuration.

**Comment by madtomic** [comment]
No, I"m talking about setting Metrics: false

**Comment by zachrocks22** [comment]
My mistake! Metrics help to support the author of the plugin, and are completely anonymous. 
If you're seeing this message, you're more than likely running a v3.X version. You can disable this message by adding "ignore-metrics-join-message" to your config, and setting it to true.

**Comment by madtomic** [comment]
Thank you for your help.
