### ISSUE TITLE
[Bug] The permissions wont work

### ISSUE THREAD

**Issue by Baktus79** [zachrocks22/ChatFeelings#6]
I have tried to set all permissions to false so the players in a specific group cant use the commands, but they still can use them. I am using Luckperms and tried to listen to what kind of permissions ChatFeelings checked for with /lp verbose. But it never checked anything.

Using Paper build 641 1.13.2
ChatFeelings 4.3

**Comment by zachrocks22** [comment]
If you wish to block the feelings for player in a specific group, make sure you are blocking:
- chatfeelings.all

**Comment by Baktus79** [comment]
![image](https://user-images.githubusercontent.com/19745447/63200084-38096f00-c080-11e9-8ca3-ac3872124c45.png)

Here you can see I added the chatfeelings.all as false to the main group. The player could still use /slap

**Comment by zachrocks22** [comment]
Hi! Could you send me your permissions file (via pastebin link on a spigot DM)? Also are you using LuckPerms Bungee or any sort of Bungeecord Network? Why this may sound silly, are you OP or have the '*' (all) permission?

**Comment by Baktus79** [comment]
Hey
Yes, I do use BungeeCord for my servers. The player that typed the /slap command is my alt account, a player with basic perms. No OP. Luckperms data is stored at a MySQL server. I can show you whats on the specific group if you like.

https://hastebin.com/goriwiyiyo.css

**Comment by Baktus79** [comment]
May I also add that this has not been an issue on earlier versions. I know it used to work on ChatFeelings v2.x. ChatFeelings v3.x and v4.x not so sure. I did run a test with v4.2.2 and it had the same issue.

**Comment by zachrocks22** [comment]
Hm. ChatFeelings v4.2 added permission definitions in the plugin.yml to help those who don't use a permission system. So I wonder if that's the issue.

Try this one last thing. Block the permission: **chatfeelings.***

**Comment by Baktus79** [comment]
Still didnt resolve the issue :( Added chatfeelings.* but nothing changed.

**Comment by Baktus79** [comment]
I went though your code and I could see that on all the places you used `hasPermission("chatfeelings.xxxx")`, they worked. Like mute, ignore, and so on. It might just be me, but I couldnt find those on the feelings commands.

**Comment by zachrocks22** [comment]
OH MY GOD. THIS IS SO EMBARRASSING THANK YOU. You are totally right. I will fix this RIGHT NOW.

**Comment by Baktus79** [comment]
hahaha, beautiful :D Coding makes blindness, so no worries :D After hours and hours words arent the same anymore.

**Comment by zachrocks22** [comment]
For real. Thank you so much for bringing that to my attention. Many apologies. This will make it's way on to spigot once I polish up the pre-build. In the mean time, you can use the v4.4-PRE2 build available under Github. This should fix this embarrassing issue! 
[https://github.com/zachrocks22/ChatFeelings/releases/tag/v4.4-PRE2](url)

**Comment by Baktus79** [comment]
Tried it, and it worked beautiful :D Thank you so much for your help!! And dont apologies. Your plugin has been loved by all my players for a long time. Its a simple great plugin that I have seen on lots of servers. Keep up the good work. Thank you for all your effort!

**Comment by zachrocks22** [comment]
Just an update that this fix is now present in the latest v4.4 release.
